kibana/entrypoint.sh

kibana should be executed with exec to give it pid 1 and bind signal forwarding with the container instance

kibana is now executed using exec

---

README.md

Explained line ending issue in kibana/entrypoint.sh on windows.

Added section about setup on windows to README.md

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Updated to latest versions of ELK and Searchguard.

ELK Stack updated to 5.2, SearchGuard and Kibana plugins updated

---

README.md
docker-compose.yml
elasticsearch/Dockerfile
elasticsearch/bin/init_sg.sh
elasticsearch/config/elasticsearch.yml
kibana/Dockerfile
kibana/config/kibana.yml
logstash/Dockerfile
logstash/config/.placeholder
logstash/pipeline/logstash.conf

Do not merge yet, I get the following error in Kibana:
```
Unhandled rejection Error: Plugin hapi-auth-cookie already registered in: http://0.0.0.0:5601
```
@floragunncom do you have any clue why?
ref #95 #96

Use new official images (Search Guard)

---

elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Update to the v5.3 release containers

---

elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Some Important Security Fixes
https://www.elastic.co/blog/elasticsearch-5-4-1-and-5-3-3-released
https://www.elastic.co/blog/kibana-5-4-1-and-5-3-3-released

Update to 5.4.1

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Release notes:
* [Elasticsearch 5.6.2 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/release-notes-5.6.2.html)
* [Logstash 5.6.2 Release Notes](https://www.elastic.co/guide/en/logstash/5.6/logstash-5-6-2.html)
* [Kibana 5.6.2 Release Notes](https://www.elastic.co/guide/en/kibana/5.6/release-notes-5.6.2.html)

Release 5.6.2

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Release 5.6.3

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Release notes:
- [Elasticsearch 6.1.0 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/release-notes-6.1.0.html)
- [Logstash 6.1.0 Release Notes](https://www.elastic.co/guide/en/logstash/6.1/logstash-6-1-0.html)
- [Kibana 6.1.0 Release Notes](https://www.elastic.co/guide/en/kibana/6.1/release-notes-6.1.0.html)
I have updated the ELK stack using the latest OSS edition

Update version to 6.1.0

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Update to 6.2.2

---

README.md

Added Host setup port requirements and Docker For Windows requirement for C: as a shared drive. Hope this helps others!

Update README.md -> clarify guidance for Docker for Windows users

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Update the searchguard branch to 6.2.2

Update Searchguard branch to 6.2.2

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>

update to 6.2.3; resolves #266

---

README.md
elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile

Release notes:
- https://www.elastic.co/guide/en/elasticsearch/reference/6.2/release-notes-6.2.4.html
- https://www.elastic.co/guide/en/logstash/current/logstash-6-2-4.html
- https://www.elastic.co/guide/en/kibana/current/release-notes-6.2.4.html

ELK Stack version updated to 6.2.4

---

README.md
elasticsearch/Dockerfile
elasticsearch/config/sg/sg_internal_users.yml
kibana/Dockerfile
logstash/Dockerfile

Upgrading to latest Search Guard version on ELK 6.3

Update ELK to version 6.3.0 and Search Guard accordingly

---

.env
README.md
docker-compose.yml
elasticsearch/Dockerfile
kibana/Dockerfile

ELK 6.4.0+ needs diffrent Search Guard versions

---

README.md

The user name should be **elastic**

Fix user name in the command of README.md

---

.env
.travis.yml
.travis/run-tests.sh
README.md
docker-compose.yml
elasticsearch/Dockerfile
elasticsearch/config/elasticsearch.yml
elasticsearch/config/sg/sg_action_groups.yml
elasticsearch/config/sg/sg_config.yml
elasticsearch/config/sg/sg_internal_users.yml
elasticsearch/config/sg/sg_roles.yml
elasticsearch/config/sg/sg_roles_mapping.yml
kibana/Dockerfile
kibana/config/kibana.yml
logstash/Dockerfile
logstash/config/logstash.yml

Same changes as in #387, but for Search Guard.
Closes #380
Closes #388

Enable Search Guard enterprise trial by default

---

extensions/apm-server/apm-server-compose.yml
extensions/curator/curator-compose.yml
extensions/logspout/logspout-compose.yml

updated docker compose versions

---

README.md

Clarify set up of built-in users

---

kibana/Dockerfile

see [search-guard-versions](https://docs.search-guard.com/latest/search-guard-versions) for new url format
closes #453

Update kibana dockerfile with new search-guard url

---

README.md

@deviantony a small one to reflect the latest changes in the rep.
Closes #467

Document supported major versions

---

README.md

Replaced block quotes with emphasis; bold for warnings, italics for information sources.
Closes #509

Replaced block quotes with emphasis; bold warnings, italic info

---

README.md

@linyongfu2013 you will probably find these instructions useful, and I believe it could help other users too.
Closes #532

Document how to reset a password

---

README.md

I tried to explain the project's philosophy in 2 short sentences, so that its aim is clear to people who visit the repo. @deviantony what do you think?
The reference to "elastdocker" is optional. I though it would be nice to provide an example of project that forked this repo and added some bells and whistles to it (lots of opinionated parameters, etc.).

Explain the project's philosophy

---

.github/workflows/ci.yml
.github/workflows/scripts/run-tests-logspout.sh
extensions/logspout/modules.go

Ensures the Logspout extension works as described in the README.
Closes #557

ci: Add test for Logspout extension

---

elasticsearch/config/sg/sg_action_groups.yml
elasticsearch/config/sg/sg_config.yml
elasticsearch/config/sg/sg_internal_users.yml
elasticsearch/config/sg/sg_roles.yml
elasticsearch/config/sg/sg_roles_mapping.yml
elasticsearch/config/sg/sg_tenants.yml

Convert all configuration files to `config_version: 2` (SG 7 format).

Convert configuration files to v2 format

---

docker-compose.yml

Automatically start elk stack after a reboot

Use restart policy unless-stopped
