README.md
Centos|Redhat is used in the example since that was the type of distribution I was on. Regardless, the note should point future readers, who might be in the same predicament, in the right direction.
=> Note about starting fig-elk when SELinux is enabled

README.md, docker-compose.yml, elasticsearch/Dockerfile, kibana/Dockerfile, kibana/config/kibana.yml, kibana/entrypoint.sh, logstash-conf/logstash.conf
Replaced logstash image with latest official image.
Manages elasticsearch container using the latest official image inside this repository.
Manages the kibana container using the latest official image inside this repository.
Updated README.
Close #1
=> Use official images

docker-compose.yml
When starting the stack `with docker-compose up`, it gives out the error:
```
ERROR: Cannot start container e032695b38cdcd1c72597004f2369a7127b8233c9ecc2320c3b2bbd10209654b: [9] System error: not a directory
```
=> Fix error "[9] System error: not a directory"

README.md, docker-compose.yml, logstash/Dockerfile, logstash/config/logstash.conf
I wasn't able to figure out another way to install logstash plugins so I created a docker build script that allows for adding plugins.
I needed to add the logstash-filter-json plugin to parse out my "message" but I could see where having this as a default for everyone would not work (ie. if they save xml in their message)
=> Feature: allow logstash plugin management

.gitattributes
=> Fix line endings issue of shell script files on Windows

docker-compose.yml, kibana/Dockerfile, kibana/entrypoint.sh
add depends_on to kibana and logstash on docker-compose.yml to prevent having to install NC and not have to keep checking for ES to start as the container will start after.
=> Use depends_on dependency container

README.md
Add note for using it running Docker for Mac.
max_map_count must be set within the xhyve virtual machine
=> Add note for max_map_count on Docker for Mac

elasticsearch/Dockerfile, kibana/Dockerfile
I wasn't able to start it from the searchguard branch due to errors saying that the search-guard plugin is not compatible with the installed elasticsearch version.
=> Update Searchguard to 5.2.2

docker-compose.yml, elasticsearch/Dockerfile, kibana/Dockerfile, kibana/config/kibana.yml, logstash/Dockerfile, logstash/config/logstash.yml
Includes required change for logstash config and disables the new machine learning functionality in x-pack by default.
=> Update to 5.4

README.md, extensions/README.md, extensions/logspout/Dockerfile, extensions/logspout/README.md, extensions/logspout/build.sh, extensions/logspout/logspout-compose.yml, extensions/logspout/modules.go
(Rebased and squashed changes from #110)
Add direct link to baked configurations, for debugging purposes.
Separate Logspout service into its own `yml`
Standardize Markdown formatting for program names
Do not auto-create indexes
Remove comments & UDP input
=> Add Logspout functionality for out-of-the-box Docker logging

README.md
I had to run "docker-compose build" after modifying Dockerfile.
Unless doing so, plugin was never added.
And I thought adding this step will help others with limited knowledge of Docker.
=> plugin readme update

README.md
`docker-compose exec` makes more sense to initialize searchguard, as all the commands using `docker-compose`.
=> docker-compose exec for searchguard initialized

-v, .travis.yml, README.md, elasticsearch/Dockerfile, elasticsearch/config/elasticsearch.yml, kibana/Dockerfile, kibana/config/kibana.yml, logstash/Dockerfile, logstash/config/logstash.yml
I have updated the ELK stack using the latest OSS edition but probably it could be useful to have different branches dedicated to the OSS and Enterprise editions.
Starting from this release to disable X-Pack we need to install the plugin and the disable it using properties. For Kibana and Logstash we can remove all the properties.
Hope this helps 😄
=> Updated the project for supporting the latest GA version 6.0.0 OSS Edition

README.md
Fix typo in "Kibana index pattern creation" section of README.md file
=> Small typo in README.md file

docker-compose.yml
Because the fs doesn't need to be write-able.
=> Make config volumes read-only

.env, README.md, docker-compose.yml, elasticsearch/Dockerfile, kibana/Dockerfile, logstash/Dockerfile
Looking at lines statistics I don't think it was worth adding 😄 
Tested on 
```
[/location] # docker --version
Docker version 1.11.2, build 781516c
[/location] # docker-compose --version
docker-compose version 1.13.0, build 1719ceb
```
Ref:  #205
=> fixing broken compatibility with Docker < 17.03

.env, README.md, docker-compose.yml, elasticsearch/Dockerfile, kibana/Dockerfile, logstash/Dockerfile
I found it easier to change the version of the ELK stack this way.
=> It is now possible to set the ELK version in the .env file.

extensions/apm-server/Dockerfile, extensions/apm-server/README.md, extensions/apm-server/apm-server-compose.yml, extensions/apm-server/config/apm-server.yml
Unsure if this of interest to you, but was doing some prototyping with Elasticsearch APM server using your elk stack and wanted to return the favor if an APM server is wanted in the stack. 
Why:
* Adds Elasticsearch Application Performance Monitoring
* Can view application traces, errors and alerts trough Kibana
How:
* Add apm-server container to the network which will receive traffic on port 8200 and report to elastic search server at port 9200
* Add a test flask app with redis to view apm tracing
=> Add APM server and APM test agent to compose file

extensions/curator/config/curator.yml
So far the included Curator configuration logs to `/usr/share/curator/curator.log`. To follow the best-practices in regards to logging inside a container, this PR proposes to log to `STDOUT`.
=> Write Curator logs to STDOUT

.env, docker-compose.yml, elasticsearch/Dockerfile, kibana/Dockerfile, logstash/Dockerfile
This project was using hardcoded `-oss` images. Playing with subscription plan features was only possible when hacking the Dockerfiles. Thus, I made the flavour configurable.
While doing this I also bumped searchguard to latest versions (separate commit, so the other change can be cherrypicked)
=> Make ELK image flavour configurable

.travis.yml, .travis/elasticsearch-setup-passwords.exp, .travis/run-tests.sh, README.md, docker-stack.yml, elasticsearch/config/elasticsearch.yml, kibana/config/kibana.yml, logstash/config/logstash.yml
We're now "secure by default" with X-Pack and paid features enabled by default 🔐 (30-day trial) 
If this gets merged, the `x-pack` branch will become the new `master` in a second step.
Closes #163
Closes #378
=> Enable Stack Features (X-Pack) and trial by default

kibana/config/kibana.yml
v7 requires slightly different syntax of the xpack security credentials to connect. `elasticsearch.username` and `elasticsearch.password` results in kibana errors not being able to authenticate. Kibana webpage continues to say "Kibana server is not ready yet" while producing the auth errors. Tested on Kibana 7.0.1
=> updating xpack credentials to v7.X.X

extensions/apm-server/config/apm-server.yml
I could not connect to the apm server with nodeJS until I made this change.
I found the solution in here https://github.com/elastic/apm-agent-nodejs/issues/256#issuecomment-367944675
=> Fixing the apm configuration

README.md, docker-compose.yml
The Compose v3 format uses a volumes syntax which is more explicit and IMO easier to understand than the v2 long colon-separated string.
It is supported since:
* [Docker 17.04.0](https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix)
We already require 17.05.0 in the README to support the `.env` input file.
* [Compose 1.12.0](https://github.com/docker/compose/releases/tag/1.12.0)
We need to bump our requirement, but that version was released in April 2017.
@deviantony do you think it's sensible?
=> Use v3 volume syntax

extensions/curator/Dockerfile
Otherwise it fails with this exception:
`elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 7.4.1 incompatible with this version of Curator (5.5.4)`
=> Update Dockerfile to use latest curator

docker-compose.yml
Hey! Thanks for your great repo on elk!
Had an issue when installing the logspout extension. We use udp to send data to logstash, but the port is opened only for tcp connections. This PR fixes that
=> Open udp logstash port 5000  for logspout

elasticsearch/config/elasticsearch.yml
Allowing the admin (user) to access Search Guard configuration GUI from kibana ! 
without this entry in the elasticsearch.yml the sg icon diapers from the left menu.
=> Allowing the admin user to access SearchGuard GUI

.github/workflows/scripts/lib/testing.sh
Remove unnecessary calls to `echo` which cause the following output in tests:
```
> Run .github/workflows/scripts/run-tests-core.sh
[+] Waiting for readiness of Elasticsearch
curl arguments: -s -D- -m3 -w %{http_code} http://172.18.0.2:9200/ -u elastic:testpasswd
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 542
```
After this change:
```
> Run .github/workflows/scripts/run-tests-core.sh
[+] Waiting for readiness of Elasticsearch
curl arguments: -s -D- -m3 -w %{http_code} http://172.18.0.2:9200/ -u elastic:testpasswd
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 542
```
=> ci: Avoid printing unnecessary empty lines

.github/workflows/ci.yml, .github/workflows/docs.yml, README.md
In an effort to reduce the usage of divisive language, GitHub has recently renamed the default Git branch from `master` to `main` for new projects, and some open-source projects are starting to catch up by renaming their default branch as well.
It would be effortless to do it in `docker-elk` because GitHub takes care of re-targeting everything to `main` seamlessly, including existing clones (with a notice printed in the terminal), as explained at https://github.com/github/renaming#renaming-existing-branches.
Considering the popularity of this project, I think this move would be generally welcomed. @deviantony what do you think?
If you approve this, you will also need to actually rename the branch at https://github.com/deviantony/docker-elk/branches before merging.
---
Examples:
```console …
```
=> Proposal: rename master branch to main

README.md, docker-compose.yml
While running on Fedora 34, with podman-compose and SELinux enabled, I was getting permission errors.
[Based on this discussion](https://github.com/containers/podman-compose/issues/256), it seems compose file doesn't allow setting [SELinux label](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) on the long syntax, so I changed the bindings to the short format.
Errors before changes:
```
2021/11/25 00:27:29 error: open /usr/share/logstash/config/logstash.yml: permission denied
1
podman start -a docker-elk_kibana_1
internal/fs/utils.js:332
throw err;
^
Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
at Object.openSync (fs.js:497:3)
at readFileSync (fs.js:393:35)
at readYaml (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_nod …
```
=> Podman and SELinux compatible volume declaration

.github/workflows/ci.yml, .github/workflows/scripts/run-tests-core.sh, README.md, docker-compose.yml, extensions/logspout/README.md, extensions/logspout/logspout-compose.yml, logstash/pipeline/logstash.conf
Mac OS Monterey is having an airplay server listening on port 5000, recommended fix is to change log stash's default listening port from 5000 to 50000 ( add one more zero) to resolve the conflict.
edit (@antoineco): fixes #739
=> fix #739 Mac OS Monterey logstash port conflict

kibana/config/kibana.yml
xpack.fleet.agents.fleet_server.hosts should be [ 'http://fleet-server:8220' ] instead of [ 'http://fleet:8220' ]
edit (antoineco): fixes #770
=> Fix default Fleet server host name in Kibana config

.github/workflows/ci.yml, .github/workflows/scripts/run-tests-fleet.sh, extensions/fleet/agent-apmserver-compose.yml, extensions/fleet/fleet-compose.yml, kibana/config/kibana.yml
Closes #773
Ref #756
Ref #761
---
~Marking as draft, I am not yet convinced we should enable this by default.
We could ship commented configurations instead, but this is messy.
It would be ideal to have an enabled/disabled flag for additional integrations such as APM Server, but Fleet doesn't have a notion of disabled integrations within agent policies.~
I repurposed the PR to enable APM Server in a separate Fleet-enrolled Elastic Agent, instead of inside the Fleet Server itself.
=> Add example of Fleet-enrolled APM Server agent

.github/workflows/ci.yml
Avoids failures while determining container IPs when the project isn't checked out in a directory named "docker-elk".
Fixes #839
=> ci: Set Compose project name

README.md
Fixed a typo error in the Readme file. the  word "accomodate" was changed to "accommadate".
=> Updated Readme.md (First pull request)
